services:
#    Monolog\Formatter\JsonFormatter:
#    Marcelmc\AwesomeBundle\Controller\TestController:
#        arguments:
#            $test: Monolog\Formatter\JsonFormatter
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    Marcelmc\AwesomeBundle\:
        resource: '../../*'
        #exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'